apiVersion: v1
entries:
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.58.0
    created: "2022-09-12T14:48:14.239108528Z"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.15.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 3.3.*
    - condition: grafana.enabled
      name: grafana
      repository: https://raw.githubusercontent.com/kaytalkcity/platform-monitor/main/charts
      version: 6.32.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
      and Prometheus rules combined with documentation and scripts to provide easy
      to operate end-to-end Kubernetes cluster monitoring with Prometheus using the
      Prometheus Operator.
    digest: 5258255db2c4c2e8d351bcc4838ec89727026085eb99c8c1a1af1326740155d1
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: andrew@quadcorps.co.uk
      name: andrewgkew
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: kube-prometheus-stack@sisti.pt
      name: GMartinez-Sisti
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - https://kaytalkcity.github.io/platform-monitor/kube-prometheus-stack-39.11.0.tgz
    version: 39.11.0
generated: "2022-09-12T14:48:14.202406757Z"
